name: Cypress Tests

on:
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    env:
      AUTH_SECRET: ${{ vars.AUTH_SECRET }}
      AUTH_URL: ${{ vars.AUTH_URL }}
      BASE_URL: ${{ vars.BASE_URL }}
      NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          config-file: cypress/cypress.dev.config.ts
          start: npm start
